# Generated by Django 4.2.13 on 2024-05-27 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_streamingplatform_watchlist_delete_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="platform",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to="api.streamingplatform",
            ),
        ),
        migrations.AlterField(
            model_name="streamingplatform",
            name="url",
            field=models.URLField(blank=True, unique=True),
        ),
    ]
